// Package manifest defines the zt.yaml format — a portable, declarative
// description of the services cfzt manages on a host. It intentionally
// excludes credentials (API token, account ID, domain — those live in
// ~/.zt-config.json, set up via `zt init`) and runtime state (tunnel ID,
// PID, status — those live in ~/.zt-state.json). A zt.yaml file is meant
// to be committed to git and replayed on a different machine via `zt apply`.
package manifest

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

// ServiceSpec describes the desired state of a single exposed service.
// It mirrors the subset of state.Tunnel that represents intent rather
// than runtime/observed state.
type ServiceSpec struct {
	Port     int      `yaml:"port,omitempty"`
	Docker   bool     `yaml:"docker,omitempty"`
	Protocol string   `yaml:"protocol,omitempty"`
	Public   bool     `yaml:"public,omitempty"`
	Allow    []string `yaml:"allow,omitempty"`
}

// Manifest is the root document of a zt.yaml file.
type Manifest struct {
	Services map[string]ServiceSpec `yaml:"services"`
}

// Load reads and parses a zt.yaml manifest from the given path.
func Load(path string) (*Manifest, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading manifest %s: %w", path, err)
	}
	var m Manifest
	if err := yaml.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("parsing manifest %s: %w", path, err)
	}
	if m.Services == nil {
		m.Services = make(map[string]ServiceSpec)
	}
	for name, svc := range m.Services {
		if !svc.Docker && svc.Port == 0 {
			return nil, fmt.Errorf("service %q: must set either 'port' or 'docker: true'", name)
		}
	}
	return &m, nil
}

// Save writes the manifest to the given path as YAML.
func Save(path string, m *Manifest) error {
	data, err := yaml.Marshal(m)
	if err != nil {
		return fmt.Errorf("encoding manifest: %w", err)
	}
	header := "# zt.yaml — portable cfzt service manifest\n" +
		"# generated by `zt export` — credentials are NOT included here.\n" +
		"# on a new machine: run `zt init` first, then `zt apply " + path + "`\n\n"
	if err := os.WriteFile(path, []byte(header+string(data)), 0644); err != nil {
		return fmt.Errorf("writing manifest %s: %w", path, err)
	}
	return nil
}
